language: c

compiler:
    - clang
    - gcc

env:
    -
    - CFLAGS='-g -O3 -Wall -Wextra -Wno-sign-compare -Werror'

install:
    - ./bootstrap
    - ./configure $CONFIGURE_OPTION
    - make

script:
    - ./pen
    - ./test.py
